name: 'Check Project Issue'

on:
  workflow_call:
    inputs:
      action_ref:
        description: "Ref for workflow or action checkout"
        required: false
        default: 'main'
        type: string

jobs:
  main:
    name: 'Check Project Issue'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout workflows'
        id: checkout_workflows
        uses: actions/checkout@v3
        with:
          repository: usf-cs272-fall2022/action-workflows
          path: 'workflows'
          ref: '${{ inputs.action_ref }}'

      - name: 'Create initial issue comment'
        id: create_comment
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./workflows/.github/scripts/issue-comment.js');
            return await script({github, context, core});

      - name: 'Parse request details'
        id: parse_request
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./workflows/.github/scripts/issue-parse.js');
            return await script({github, context, core});

      - name: 'Find relevant action run'
        id: find_action
        uses: actions/github-script@v6
        env:
          RELEASE_TAG:   '${{ steps.parse_request.outputs.release_tag }}'
          VERSION_MAJOR: '${{ steps.parse_request.outputs.version_major }}'
          VERSION_MINOR: '${{ steps.parse_request.outputs.version_minor }}'
          VERSION_PATCH: '${{ steps.parse_request.outputs.version_patch }}'
        with:
          script: |
            const script = require('./workflows/.github/scripts/issue-action.js');
            return await script({github, context, core});

      - name: 'Verify request is valid'
        id: verify_request
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./workflows/.github/scripts/issue-verify.js');
            return await script({github, context, core});

      - name: 'Update issue with success'
        id: update_success
        if: ${{ success() }}
        uses: actions/github-script@v6
        env:
          COMMENT_ID: '${{ steps.create_comment.outputs.comment_id }}'
        with:
          script: |
            core.info('Hello world.');
            core.setFailed('Not yet implemented.');

      - name: 'Update issue with failure'
        id: update_failure
        if: ${{ failure() || cancelled() }}
        uses: actions/github-script@v6
        env:
          COMMENT_ID: '${{ steps.create_comment.outputs.comment_id }}'
          RESULTS: ${{ toJSON(steps) }}
        with:
          script: |
            const script = require('./workflows/.github/scripts/issue-failure.js');
            return await script({github, context, core});