name: 'Check Project Issue'

on:
  workflow_call:

jobs:
  main:
    name: 'Testing'
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Hello"
      - run: echo "${{ toJson(github.event) }}"