name: 'Check Compile'

on:
  workflow_call:
    inputs:
      user_repo:
        description: "Repository with user project code"
        required: true
        type: string
      
      test_repo:
        description: "Repository with test project code"
        required: true
        type: string
      
      user_cache:
        description: "Commit SHA of project code"
        required: true
        type: string
      
      test_cache:
        description: "Commit SHA of test code"
        required: true
        type: string

      user_path:
        description: "Path to user project code"
        required: true
        type: string
        default: "project-main"
      
      test_path:
        description: "Path to test project code"
        required: true
        type: string
        default: "project-tests"

      test_tag:
        description: "Tag for which tests to run"
        required: true
        type: string

jobs:
  main:
    name: '.'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 'Checkout workflows'
        id: checkout-workflows
        uses: actions/checkout@v3
        with:
          repository: usf-cs272-fall2022/action-workflows
          path: 'workflows'

      - name: 'Setup project code'
        uses: ./workflows/.github/actions/project-setup
        with:
          user_repo:  '${{ inputs.user_repo }}'
          test_repo:  '${{ inputs.test_repo }}'
          user_path:  '${{ inputs.user_path }}'
          test_path:  '${{ inputs.test_path }}'
          user_cache: '${{ inputs.user_cache }}'
          test_cache: '${{ inputs.test_cache }}'

      - name: 'Compile project code' 
        working-directory: '${{ inputs.user_path }}'
        run: |
          RUN_STATUS=0
          mvn -ntp -DcompileOptionXlint=-Xlint:none -DcompileOptionXdoclint=-Xdoclint:none -Dmaven.compiler.showWarnings=false -DcompileOptionFail=false compile test-compile || RUN_STATUS=$?
          if [[ RUN_STATUS -ne 0 ]]; then
            echo "::error ::Unable to compile your project source code."
            exit 1
          fi

      - name: 'Run project tests'
        working-directory: '${{ inputs.user_path }}'
        env:
          TEST_TAG: ${{ inputs.test_tag }}
        run: |
          RUN_STATUS=0
          mvn -ntp -Dgroups="${TEST_TAG}" test || RUN_STATUS=$?
          if [[ RUN_STATUS -ne 0 ]]; then
            echo "::error ::One or more tests did not pass."
            exit 1
          fi