name: 'Project Review'

on:
  workflow_call:

jobs:
  main:
    name: 'Run'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('This action is not yet supported.');

