name: 'Check Project Label'

on:
  workflow_call:

jobs:
  main:
    name: 'Check'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Workflows'
        id: checkout-workflows
        uses: actions/checkout@v3
        with:
          repository: usf-cs272-fall2022/action-workflows
          path: 'workflows'

      - name: 'Check Event'
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./workflows/scripts/check-event-labeled.js');
            return await script({github, context, core});
