name: 'Check Style'

on:
  workflow_call:
    inputs:
      user_repo:
        description: "Repository with user project code"
        required: true
        type: string
      
      user_path:
        description: "Path to user project code"
        required: true
        type: string
        default: "project-main"

      user_cache:
        description: "Commit SHA of project code"
        required: true
        type: string

    outputs:
      status:
        description: "Status of each step in this workflow"
        value: ${{ jobs.main.outputs.status }}

jobs:
  main:
    name: 'Style'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    outputs:
      status: ${{ steps.step_status.outputs.status }}

    steps:
      - name: 'Checkout workflows'
        id: checkout_workflows
        uses: actions/checkout@v3
        with:
          repository: usf-cs272-fall2022/action-workflows
          path: 'workflows'

      - name: 'Setup project code'
        id: setup_project_code
        uses: ./workflows/.github/actions/project-setup
        with:
          user_repo:  '${{ inputs.user_repo }}'
          user_path:  '${{ inputs.user_path }}'
          user_cache: '${{ inputs.user_cache }}'
          setup_java: 'false'

      - name: 'Check extra main methods'
        uses: actions/github-script@v6
        id: check_main_methods
        env:
          USER_PATH: '${{ inputs.user_path }}'
        with:
          script: |
            const command = 'grep'
            const args = ['-rnoE', '--exclude=Driver.java', "'\s*public\s+static\s+void\s+main\s*\('"];
            const options = {
              ignoreReturnCode: true,
              cwd: `${process.env.USER_PATH}/src/main/java`
            };
            const result = await exec.exec(command, args, options);

            if (result !== 0) {
              core.setFailed(`Except for Driver.java, you should delete old main methods from your code.`);
            }
      
      - name: 'Save step status'
        id: step_status
        uses: actions/github-script@v6
        if: ${{ always() }}
        env:
          STEP_STATUS: ${{ toJSON(steps) }}
        with:
          script: |
            core.setOutput('status', process.env.STEP_STATUS);
            core.info(process.env.STEP_STATUS);
