name: 'Check Warnings'

on:
  workflow_call:
    inputs:
      user_repo:
        description: "Repository with user project code"
        required: true
        type: string
      
      user_path:
        description: "Path to user project code"
        required: true
        type: string
        default: "project-main"

      user_cache:
        description: "Commit SHA of project code"
        required: true
        type: string

jobs:
  main:
    name: 'Warnings'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 'Checkout workflows'
        id: checkout-workflows
        uses: actions/checkout@v3
        with:
          repository: usf-cs272-fall2022/action-workflows
          path: 'workflows'

      - name: 'Setup project code'
        uses: ./workflows/.github/actions/project-setup
        with:
          user_repo:  '${{ inputs.user_repo }}'
          user_path:  '${{ inputs.user_path }}'
          user_cache: '${{ inputs.user_cache }}'

      - name: 'Compile source code'
        working-directory: '${{ inputs.user_path }}'
        run: |
          RUN_STATUS=0
          mvn -ntp -DcompileOptionXlint=-Xlint:all,-processing -DcompileOptionXdoclint=-Xdoclint:none -Dmaven.compiler.showWarnings=true -DcompileOptionFail=true clean compile || RUN_STATUS=$?
          if [[ RUN_STATUS -ne 0 ]]; then
            echo "::error ::Unable to compile the project source code without warnings."
            exit 1
          fi

      - name: 'Compile Javadoc comments'
        working-directory: '${{ inputs.user_path }}'
        run: |
          RUN_STATUS=0
          mvn -ntp -DcompileOptionXlint=-Xlint:preview -DcompileOptionXdoclint=-Xdoclint:all/private -Dmaven.compiler.showWarnings=true -DcompileOptionFail=true clean compile || RUN_STATUS=$?
          if [[ RUN_STATUS -ne 0 ]]; then
            echo "::error ::Unable to compile the project source code without Javadoc warnings."
            exit 1
          fi