name: 'Project Results'

on:
  workflow_call:
    inputs:
      results:
        description: "Results from previous jobs"
        required: true
        type: string

      release_id:
        description: "Project release version id (not tag)"
        required: true
        type: string

jobs:
  main:
    name: 'Results'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 'Output results'
        env:
          RESULTS: ${{ inputs.results }}
        run: echo ${RESULTS}

      - name: 'Update release'
        id: update_release
        uses: actions/github-script@v6
        env:
          RELEASE_ID: ${{ inputs.release_id }}
        with:
          script: |
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              rep: context.repo.repo,
              release_id: process.env.RELEASE_ID,
              body: `See [run #${context.runNumber} (id ${context.runId})](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.`
            });
