name: 'Project Results'

on:
  workflow_call:
    inputs:
      results:
        description: "Results from previous jobs"
        required: true
        type: string

      release_id:
        description: "Project release version id (not tag)"
        required: true
        type: string

jobs:
  main:
    name: 'Results'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 'Output results'
        env:
          RESULTS: ${{ inputs.results }}
        run: echo ${RESULTS}

