name: 'Check Compile'

on:
  workflow_call:
    inputs:
      user_repo:
        description: "Repository with user project code"
        required: true
      
      test_repo:
        description: "Repository with test project code"
        required: true
      
      user_cache:
        description: "Commit SHA of project code"
        required: true
      
      test_cache:
        description: "Commit SHA of test code"
        required: true

      user_path:
        description: "Path to user project code"
        required: true
        default: "project-main"
      
      test_path:
        description: "Path to test project code"
        required: true
        default: "project-tests"

jobs:
  main:
    name: 'Main'
    runs-on: ubuntu-latest
    timeout-minutes: 1 

    steps:
      - name: 'Checkout workflows'
        id: checkout-workflows
        uses: actions/checkout@v3
        with:
          repository: usf-cs272-fall2022/action-workflows
          path: 'workflows'

      - name: 'Setup project code'
        uses: ./workflows/.github/actions/project-setup
        with:
          user_repo:  '${{ inputs.user_repo }}'
          test_repo:  '${{ inputs.test_repo }}'
          user_path:  '${{ inputs.user_path }}'
          test_path:  '${{ inputs.test_path }}'
          user_cache: '${{ inputs.user_cache }}'
          test_cache: '${{ inputs.test_cache }}'

      - name: 'Compile project code' 
        working-directory: '${{ inputs.user_path }}'
        run: |
          RUN_STATUS=0
          mvn -ntp -DcompileOptionXlint=-Xlint:none -DcompileOptionXdoclint=-Xdoclint:none -Dmaven.compiler.showWarnings=false -DcompileOptionFail=false compile || RUN_STATUS=$?
          if [[ RUN_STATUS -ne 0 ]]; then
            echo "::error ::Unable to compile your project source code."
            exit 1
          fi

      - name: 'Listing source code'
        working-directory: '${{ inputs.user_path }}'
        run: |
          ls -ACGR target/classes

      - name: 'Compile test code' 
        working-directory: '${{ inputs.user_path }}'
        run: |
          RUN_STATUS=0
          mvn -ntp -DcompileOptionXlint=-Xlint:none -DcompileOptionXdoclint=-Xdoclint:none -Dmaven.compiler.showWarnings=false -DcompileOptionFail=false test-compile || RUN_STATUS=$?
          if [[ RUN_STATUS -ne 0 ]]; then
            echo "::error ::Unable to compile the project test code."
            exit 1
          fi

      - name: 'Listing test code'
        working-directory: '${{ inputs.user_path }}'
        run: |
          ls -ACGR target/test-classes