name: 'Request Project Grade'

on:
  workflow_call:

jobs:
  main:
    name: 'Run'

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('This action is not yet supported.');

