name: 'Check Project Issue'

on:
  workflow_call:

jobs:
  main:
    name: 'Check Project Issue'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('This action is not yet supported.');
