name: 'Check Project Issue'

on:
  workflow_call:
    inputs:
      action_ref:
        description: "Ref for workflow or action checkout"
        required: false
        default: 'main'
        type: string

jobs:
  main:
    name: 'Check Project Issue'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout workflows'
        id: checkout_workflows
        uses: actions/checkout@v3
        with:
          repository: usf-cs272-fall2022/action-workflows
          path: 'workflows'
          ref: '${{ inputs.action_ref }}'
