name: 'Check Warnings'

on:
  workflow_call:
    inputs:
      user_repo:
        description: "Repository with user project code"
        required: true
        type: string
      
      user_path:
        description: "Path to user project code"
        required: true
        type: string
        default: "project-main"

      user_cache:
        description: "Commit SHA of project code"
        required: true
        type: string

    outputs:
      status:
        description: "Status of each step in this workflow"
        value: ${{ jobs.main.outputs.status }}

jobs:
  main:
    name: 'Warnings'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    outputs:
      status: ${{ steps.step_status.outputs.status }}

    steps:
      - name: 'Checkout workflows'
        id: checkout_workflows
        uses: actions/checkout@v3
        with:
          repository: usf-cs272-fall2022/action-workflows
          path: 'workflows'

      - name: 'Setup project code'
        id: setup_project_code
        uses: ./workflows/.github/actions/project-setup
        with:
          user_repo:  '${{ inputs.user_repo }}'
          user_path:  '${{ inputs.user_path }}'
          user_cache: '${{ inputs.user_cache }}'
          setup_java: 'true'
          
      - name: 'Compile source code'
        id: compile_source_code
        working-directory: '${{ inputs.user_path }}'
        run: |
          # RUN_STATUS=0
          mvn -ntp -DcompileOptionXlint=-Xlint:all,-processing -DcompileOptionXdoclint=-Xdoclint:none -Dmaven.compiler.showWarnings=true -DcompileOptionFail=true clean compile #|| RUN_STATUS=$?
          # if [[ RUN_STATUS -ne 0 ]]; then
          #   echo "::error ::Unable to compile the project source code without warnings."
          #   exit 1
          # fi

      - name: 'Compile Javadoc comments'
        id: compile_javadoc_comments
        working-directory: '${{ inputs.user_path }}'
        run: |
          # RUN_STATUS=0
          mvn -ntp -DcompileOptionXlint=-Xlint:preview -DcompileOptionXdoclint=-Xdoclint:all/private -Dmaven.compiler.showWarnings=true -DcompileOptionFail=true clean compile #|| RUN_STATUS=$?
          # if [[ RUN_STATUS -ne 0 ]]; then
          #   echo "::error ::Unable to compile the project source code without Javadoc warnings."
          #   exit 1
          # fi

      - name: 'Save step status'
        id: step_status
        uses: actions/github-script@v6
        if: ${{ always() }}
        env:
          STEP_STATUS: ${{ toJSON(steps) }}
        with:
          script: |
            core.setOutput('status', process.env.STEP_STATUS);
            core.info(process.env.STEP_STATUS);