name: 'Project Results'

on:
  workflow_call:
    inputs:
      action_ref:
        description: "Ref for workflow or action checkout"
        required: false
        default: 'main'
        type: string

      release_id:
        description: "Project release version id (not tag)"
        required: true
        type: string

      # version information
      version_major:
        description: "The major version number (i.e. project number) from the release tag"
        required: true
        type: string

      version_minor:
        description: "The minor version number (i.e. code review number) from the release tag"
        required: true
        type: string

      version_patch:
        description: "The patch version number from the release tag"
        required: true
        type: string

      # results from other jobs and steps
      results:
        description: "Results from previous jobs"
        required: true
        type: string

jobs:
  main:
    name: 'Results'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 'Checkout workflows'
        id: checkout_workflows
        uses: actions/checkout@v3
        with:
          repository: usf-cs272-fall2022/action-workflows
          path: 'workflows'
          ref: '${{ inputs.action_ref }}'

      - name: 'Check and save eligibility'
        id: check_review
        uses: actions/github-script@v6
        env:
          RELEASE_TAG:   '${{ inputs.release_tag }}'
          VERSION_MAJOR: '${{ inputs.version_major }}'
          VERSION_MINOR: '${{ inputs.version_minor }}'
          VERSION_PATCH: '${{ inputs.version_patch }}'
        with:
          script: |
            const artifact = require('@actions/artifact');
            const fs = require('fs');

            const script = require('./workflows/.github/scripts/release-results.js');
            return await script({github, context, core, fs, artifact});

