name: 'Check Style'

on:
  workflow_call:
    inputs:
      user_repo:
        description: "Repository with user project code"
        required: true
        type: string
      
      user_path:
        description: "Path to user project code"
        required: true
        type: string
        default: "project-main"

      user_cache:
        description: "Commit SHA of project code"
        required: true
        type: string

    outputs:
      status:
        description: "Status of each step in this workflow"
        value: ${{ jobs.main.outputs.status }}

jobs:
  main:
    name: 'Style'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    outputs:
      status: ${{ steps.step_status.outputs.status }}

    steps:
      - name: 'Checkout workflows'
        id: checkout_workflows
        uses: actions/checkout@v3
        with:
          repository: usf-cs272-fall2022/action-workflows
          path: 'workflows'

      - name: 'Setup project code'
        id: setup_project_code
        uses: ./workflows/.github/actions/project-setup
        with:
          user_repo:  '${{ inputs.user_repo }}'
          user_path:  '${{ inputs.user_path }}'
          user_cache: '${{ inputs.user_cache }}'
          setup_java: 'false'

      # Uses github-script and exec instead of bash for better output than "Process returned exit code 1."

      - name: 'Check extra main methods'
        uses: actions/github-script@v6
        id: check_main_methods
        env:
          USER_PATH: '${{ inputs.user_path }}'
        with:
          script: |
            const script = require('./workflows/.github/scripts/run-exec.js');
            return await script({exec, core});

      - name: 'Check extra main methods'
        if: ${{ always() }}
        working-directory: '${{ inputs.user_path }}/src/main/java'
        run: |
          RUN_STATUS=0
          grep -rnoE --exclude=Driver.java '\s*public\s+static\s+void\s+main\s*\(' || RUN_STATUS=$?
          if [[ RUN_STATUS -ne 1 ]]; then
            echo "::error ::Except for Driver.java, you should delete old main methods from your code."
            exit 1
          fi
          echo "Found 0 main methods."


      - name: 'Save step status'
        id: step_status
        uses: actions/github-script@v6
        if: ${{ always() }}
        env:
          STEP_STATUS: ${{ toJSON(steps) }}
        with:
          script: |
            core.setOutput('status', process.env.STEP_STATUS);
            core.info(process.env.STEP_STATUS);
