name: 'Check Compile'

on:
  workflow_call:
    inputs:
      user_repo:
        description: "Repository with user project code"
        required: true
        type: string
      
      user_path:
        description: "Path to user project code"
        required: true
        type: string
        default: "project-main"

      user_cache:
        description: "Commit SHA of project code"
        required: true
        type: string
      
      test_repo:
        description: "Repository with test project code"
        required: true
        type: string
      
      test_path:
        description: "Path to test project code"
        required: true
        type: string
        default: "project-tests"

      test_cache:
        description: "Commit SHA of test code"
        required: true
        type: string

    outputs:
      status:
        description: "Status of each step in this workflow"
        value: ${{ jobs.main.outputs.status }}

jobs:
  main:
    name: 'Compile'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    outputs:
      status: ${{ steps.step_status.outputs.status }}

    steps:
      - name: 'Checkout workflows'
        id: checkout_workflows
        uses: actions/checkout@v3
        with:
          repository: usf-cs272-fall2022/action-workflows
          path: 'workflows'

      - name: 'Setup project code'
        id: setup_project_code
        uses: ./workflows/.github/actions/project-setup
        with:
          user_repo:  '${{ inputs.user_repo }}'
          user_path:  '${{ inputs.user_path }}'
          user_cache: '${{ inputs.user_cache }}'
          test_repo:  '${{ inputs.test_repo }}'
          test_path:  '${{ inputs.test_path }}'
          test_cache: '${{ inputs.test_cache }}'
          setup_java: 'true'

      - name: 'Compile project code'
        id: compile_project_code
        working-directory: '${{ inputs.user_path }}'
        run: |
          # RUN_STATUS=0
          mvn -ntp -DcompileOptionXlint=-Xlint:none -DcompileOptionXdoclint=-Xdoclint:none -Dmaven.compiler.showWarnings=false -DcompileOptionFail=false compile #|| RUN_STATUS=$?
          # if [[ RUN_STATUS -ne 0 ]]; then
          #   echo "::error ::Unable to compile your project source code."
          #   exit 1
          # fi

      - name: 'Listing project code'
        id: list_project_code
        working-directory: '${{ inputs.user_path }}'
        run: |
          ls -ACGR target/classes

      - name: 'Compile test code' 
        working-directory: '${{ inputs.user_path }}'
        id: compile_test_code
        run: |
          # RUN_STATUS=0
          mvn -ntp -DcompileOptionXlint=-Xlint:none -DcompileOptionXdoclint=-Xdoclint:none -Dmaven.compiler.showWarnings=false -DcompileOptionFail=false test-compile #|| RUN_STATUS=$?
          # if [[ RUN_STATUS -ne 0 ]]; then
          #   echo "::error ::Unable to compile the project test code."
          #   exit 1
          # fi

      - name: 'Listing test code'
        id: list_test_code
        working-directory: '${{ inputs.user_path }}'
        run: |
          ls -ACGR target/test-classes
      
      - name: 'Save step status'
        id: step_status
        uses: actions/github-script@v6
        if: ${{ always() }}
        env:
          STEP_STATUS: ${{ toJSON(steps) }}
        with:
          script: |
            core.setOutput('status', process.env.STEP_STATUS);
            core.info(process.env.STEP_STATUS);
